#Routes configuration

home:
  path: /
  controller: App\Controller\MainController::index

post_add:
  path: /add
  controller: App\Controller\MainController::add

post_show:
  path: /show/{id}
  controller: App\Controller\MainController::show

post_edit:
  path: /edit/{id}
  controller: App\Controller\MainController::edit
  requirements:
    id: '\d+'
  
post_delete:
  path: /delete/{id}
  controller: App\Controller\MainController::delete
  requirements:
    id: '\d+' 
