#Routes configuration

home:
  path: /
  controller: App\Controller\MainController::index

post_add:
  path: /add
  controller: App\Controller\MainController::add

post_show:
  path: /show/{id}
  controller: App\Controller\MainController::show

post_edit:
  path: /edit/{id}
  controller: App\Controller\MainController::edit
  
post_remove:
  path: /remove/{id}
  controller: App\Controller\MainController::remove  
