#Routes configuration

home:
  path: /
  controller: App\Controller\MainController::index

post_add:
  path: /post/add
  controller: App\Controller\MainController::add

post_show:
  path: /post/show/{id}
  controller: App\Controller\MainController::show

post_edit:
  path: /post/edit/{id}
  controller: App\Controller\MainController::edit
  requirements:
    id: '\d+'

post_delete:
  path: /post/delete/{id}
  controller: App\Controller\MainController::delete
  requirements:
    id: '\d+'

admin:
  path: /admin
  controller: App\Controller\AdminController::admin

users:
  path: /admin/users
  controller: App\Controller\AdminController::users

posts:
  path: /admin/posts
  controller: App\Controller\AdminController::posts

about:
  path: /about
  controller: App\Controller\MainController::about

user:
  path: /user/{id}
  controller: App\Controller\UserController::index
  requirements:
    id: '\d+'

user_edit:
  path: /user/edit/{id}
  controller: App\Controller\UserController::edit
  requirements:
    id: '\d+'

user_delete:
  path: /user/delete/{id}
  controller: App\Controller\UserController::delete
  requirements:
    id: '\d+'

category:
  path: /admin/category
  controller: App\Controller\CategoryController::index

category_add:
  path: /admin/category/add
  controller: App\Controller\CategoryController::add

category_edit:
  path: /admin/category/edit/{id}
  controller: App\Controller\CategoryController::edit
  requirements:
    id: '\d+'

category_delete:
  path: /admin/category/delete/{id}
  controller: App\Controller\CategoryController::delete
  requirements:
    id: '\d+'
