#Routes configuration

home:
  path: /
  controller: App\Controller\MainController::index

post_add:
  path: /post/add
  controller: App\Controller\MainController::add

post_show:
  path: /post/show/{id}
  controller: App\Controller\MainController::show

post_edit:
  path: /post/edit/{id}
  controller: App\Controller\MainController::edit
  requirements:
    id: '\d+'
  
post_delete:
  path: /post/delete/{id}
  controller: App\Controller\MainController::delete
  requirements:
    id: '\d+' 

admin:
  path: /admin
  controller: App\Controller\AdminController::admin

about:
  path: /about
  controller: App\Controller\MainController::about 
